# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/demo.Greeter/SayHello',
                request_serializer=service__pb2.HelloRequest.SerializeToString,
                response_deserializer=service__pb2.HelloReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """定义服务
    """

    def SayHello(self, request, context):
        """发送一个招呼
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=service__pb2.HelloRequest.FromString,
                    response_serializer=service__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """定义服务
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Greeter/SayHello',
            service__pb2.HelloRequest.SerializeToString,
            service__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BacktesterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartBacktest = channel.unary_unary(
                '/demo.Backtester/StartBacktest',
                request_serializer=service__pb2.BacktestRequest.SerializeToString,
                response_deserializer=service__pb2.BacktestResultReply.FromString,
                _registered_method=True)
        self.GetAllBacktestResults = channel.unary_unary(
                '/demo.Backtester/GetAllBacktestResults',
                request_serializer=service__pb2.BacktestRequest.SerializeToString,
                response_deserializer=service__pb2.BacktestListReply.FromString,
                _registered_method=True)
        self.GetTargetBacktestResult = channel.unary_unary(
                '/demo.Backtester/GetTargetBacktestResult',
                request_serializer=service__pb2.BacktestRequest.SerializeToString,
                response_deserializer=service__pb2.BacktestResultReply.FromString,
                _registered_method=True)
        self.StartTest = channel.unary_unary(
                '/demo.Backtester/StartTest',
                request_serializer=service__pb2.BacktestRequest.SerializeToString,
                response_deserializer=service__pb2.BacktestResultReply.FromString,
                _registered_method=True)


class BacktesterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBacktestResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTargetBacktestResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktesterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBacktest,
                    request_deserializer=service__pb2.BacktestRequest.FromString,
                    response_serializer=service__pb2.BacktestResultReply.SerializeToString,
            ),
            'GetAllBacktestResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBacktestResults,
                    request_deserializer=service__pb2.BacktestRequest.FromString,
                    response_serializer=service__pb2.BacktestListReply.SerializeToString,
            ),
            'GetTargetBacktestResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTargetBacktestResult,
                    request_deserializer=service__pb2.BacktestRequest.FromString,
                    response_serializer=service__pb2.BacktestResultReply.SerializeToString,
            ),
            'StartTest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTest,
                    request_deserializer=service__pb2.BacktestRequest.FromString,
                    response_serializer=service__pb2.BacktestResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.Backtester', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.Backtester', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Backtester(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Backtester/StartBacktest',
            service__pb2.BacktestRequest.SerializeToString,
            service__pb2.BacktestResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBacktestResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Backtester/GetAllBacktestResults',
            service__pb2.BacktestRequest.SerializeToString,
            service__pb2.BacktestListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTargetBacktestResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Backtester/GetTargetBacktestResult',
            service__pb2.BacktestRequest.SerializeToString,
            service__pb2.BacktestResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.Backtester/StartTest',
            service__pb2.BacktestRequest.SerializeToString,
            service__pb2.BacktestResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GatewayManagerStub(object):
    """gateway管理
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddGateway = channel.unary_unary(
                '/demo.GatewayManager/AddGateway',
                request_serializer=service__pb2.GatewayRequest.SerializeToString,
                response_deserializer=service__pb2.GatewayReply.FromString,
                _registered_method=True)
        self.SendOrder = channel.unary_unary(
                '/demo.GatewayManager/SendOrder',
                request_serializer=service__pb2.SendOrderRequest.SerializeToString,
                response_deserializer=service__pb2.SendOrderReply.FromString,
                _registered_method=True)


class GatewayManagerServicer(object):
    """gateway管理
    """

    def AddGateway(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddGateway': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGateway,
                    request_deserializer=service__pb2.GatewayRequest.FromString,
                    response_serializer=service__pb2.GatewayReply.SerializeToString,
            ),
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=service__pb2.SendOrderRequest.FromString,
                    response_serializer=service__pb2.SendOrderReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.GatewayManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.GatewayManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayManager(object):
    """gateway管理
    """

    @staticmethod
    def AddGateway(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.GatewayManager/AddGateway',
            service__pb2.GatewayRequest.SerializeToString,
            service__pb2.GatewayReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.GatewayManager/SendOrder',
            service__pb2.SendOrderRequest.SerializeToString,
            service__pb2.SendOrderReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EventEngineStub(object):
    """事件引擎
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeEvents = channel.unary_stream(
                '/demo.EventEngine/SubscribeEvents',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.EventReply.FromString,
                _registered_method=True)


class EventEngineServicer(object):
    """事件引擎
    """

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.EventReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.EventEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.EventEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventEngine(object):
    """事件引擎
    """

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/demo.EventEngine/SubscribeEvents',
            service__pb2.Empty.SerializeToString,
            service__pb2.EventReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncData = channel.unary_unary(
                '/demo.DataManager/SyncData',
                request_serializer=service__pb2.SyncDataRequest.SerializeToString,
                response_deserializer=service__pb2.SyncDataReply.FromString,
                _registered_method=True)
        self.GetOverview = channel.unary_unary(
                '/demo.DataManager/GetOverview',
                request_serializer=service__pb2.GetOverviewRequest.SerializeToString,
                response_deserializer=service__pb2.GetOverviewListReply.FromString,
                _registered_method=True)


class DataManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncData': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncData,
                    request_deserializer=service__pb2.SyncDataRequest.FromString,
                    response_serializer=service__pb2.SyncDataReply.SerializeToString,
            ),
            'GetOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverview,
                    request_deserializer=service__pb2.GetOverviewRequest.FromString,
                    response_serializer=service__pb2.GetOverviewListReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.DataManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.DataManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.DataManager/SyncData',
            service__pb2.SyncDataRequest.SerializeToString,
            service__pb2.SyncDataReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.DataManager/GetOverview',
            service__pb2.GetOverviewRequest.SerializeToString,
            service__pb2.GetOverviewListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConfigureManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveConfig = channel.unary_unary(
                '/demo.ConfigureManager/SaveConfig',
                request_serializer=service__pb2.SaveConfigListRequest.SerializeToString,
                response_deserializer=service__pb2.SaveConfigReply.FromString,
                _registered_method=True)
        self.LoadConfig = channel.unary_unary(
                '/demo.ConfigureManager/LoadConfig',
                request_serializer=service__pb2.LoadConfigRequest.SerializeToString,
                response_deserializer=service__pb2.LoadConfigReply.FromString,
                _registered_method=True)


class ConfigureManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigureManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveConfig,
                    request_deserializer=service__pb2.SaveConfigListRequest.FromString,
                    response_serializer=service__pb2.SaveConfigReply.SerializeToString,
            ),
            'LoadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadConfig,
                    request_deserializer=service__pb2.LoadConfigRequest.FromString,
                    response_serializer=service__pb2.LoadConfigReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.ConfigureManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.ConfigureManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigureManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.ConfigureManager/SaveConfig',
            service__pb2.SaveConfigListRequest.SerializeToString,
            service__pb2.SaveConfigReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.ConfigureManager/LoadConfig',
            service__pb2.LoadConfigRequest.SerializeToString,
            service__pb2.LoadConfigReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
